version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/todo_db
    depends_on:
      - mongo
    networks:
      - todo-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=todo_db
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
